# Generated by Django 5.2.7 on 2025-10-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the task.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A detailed description of the task.', null=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', help_text='The current status of the task.', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='The due date for the task.', null=True)),
                ('estimated_effort', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated effort in hours.', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependencies', models.ManyToManyField(blank=True, help_text='Tasks that this task depends on.', to='task.task')),
            ],
        ),
    ]
