# Generated by Django 5.2.7 on 2025-11-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('hold', 'On Hold'), ('waiting', 'Waiting')], default='todo', help_text='The current status of the task.', max_length=20),
        ),
    ]
