# Generated by Django 5.2.7 on 2025-11-01 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='The parent task of this task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='task.task'),
        ),
    ]
